language: scala
sudo: required

scala:
   - 2.12.2

jdk:
  - oraclejdk8

services:
  - docker

script: "sbt clean coverage core/test api/test core/it:test api/it:test coverageReport"
after_success: "sbt coverageAggregate coveralls"