/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_id_tmm_senatedb_countengine_CountEngineInterface__ */

#ifndef _Included_au_id_tmm_senatedb_countengine_CountEngineInterface__
#define _Included_au_id_tmm_senatedb_countengine_CountEngineInterface__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_id_tmm_senatedb_countengine_CountEngineInterface__
 * Method:    count
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_au_id_tmm_senatedb_countengine_CountEngineInterface_00024_count
  (JNIEnv *, jobject, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
