version: "3.3"

volumes:
  backend-db-data:
  raw-data:

secrets:
  backend-db-password:

services:
  api:
    image: tmccarthy/ausvotes-api:${AUSVOTES_VERSION:-latest}

    environment:
      # API environment variables
      PORT: 80
      JAVA_OPTS: -Xmx256m

      # Backend environment variables
      DB_DEFAULT_PASSWORD_FILE: /run/secrets/backend-db-password
      DB_DEFAULT_URL: jdbc:postgresql://backend_db/ausvotes_backend

    expose:
      - "80"

    secrets:
      - backend-db-password

  backend_db:
    image: tmccarthy/ausvotes-backend-database:${AUSVOTES_VERSION:-latest}
    environment:
      POSTGRES_DB: ausvotes_backend
      POSTGRES_USER: ausvotes_backend
      POSTGRES_PASSWORD_FILE: /run/secrets/backend-db-password

    expose:
      - 5432

    volumes:
      - backend-db-data:/var/lib/postgresql/data

    secrets:
      - backend-db-password

  backend_db_migration:
    image: tmccarthy/ausvotes-backend-db-migration:${AUSVOTES_VERSION:-latest}
    environment:
      DB_DEFAULT_PASSWORD_FILE: /run/secrets/backend-db-password
      DB_DEFAULT_URL: jdbc:postgresql://backend_db/ausvotes_backend
      JAVA_OPTS: -Xmx1024m

    volumes:
      - raw-data:/opt/ausvotes-api/rawData

    secrets:
      - backend-db-password